### ISSUE TITLE
Akun Github

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/TP5113#1]
Nama - NRP - Akun Github
contoh
Sevi Nurafni 12345 @sevinurafni

**Comment by silvinf** [comment]
Silvi Nurul Fazri _2C3220001 https://github.com/silvinf

**Comment by Wulan2C3220002** [comment]
Wulan Hidayah - 2C3220002 @[wulan2C3220002](https://github.com/Wulan2C3220002)

**Comment by Liana301103** [comment]
Liana Kuswardhani - 2C3220003 - @Liana301103

**Comment by dilan1212** [comment]
dilan satria - 2C3220007 https://github.com/dilan1212

**Comment by faqihtafaquh** [comment]
Faqih Tafaquh Fidin_2C3220006 @faqihtafaquh

**Comment by adiriadi04** [comment]
nama adi riadi
NRP2c3220005
@adiriadi04

**Comment by Rizkifajar5** [comment]
Rizki Fajar Ramadan_2C3220008_ @Rizkifajar5
