### ISSUE TITLE
Tugas 2

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/TP5113#5]

**Comment by silvinf** [comment]
[Uploading Silvi Nurul Fazri_2C3220001.pdf…]()

**Comment by silvinf** [comment]
[Uploading Silvi Nurul Fazri_3C3220001.pdf…]()

**Comment by silvinf** [comment]
[Uploading Silvi Nurul Fazri_3C3220001.pdf…]()

**Comment by Wulan2C3220002** [comment]
[T2_Wulan Hidayah_Latar Belakang.pdf](https://github.com/user-attachments/files/17388677/T2_Wulan.Hidayah_Latar.Belakang.pdf)

**Comment by silvinf** [comment]
[Uploading Silvi Nurul Fazri_3C3220001.pdf…]()

**Comment by silvinf** [comment]
[T2_Silvi Nurul Fazri_2C3220001.pdf](https://github.com/user-attachments/files/17388629/T2_Silvi.Nurul.Fazri_2C3220001.pdf)

**Comment by adiriadi04** [comment]
[2AdiRiadi_2C3220005_TEKPANG.pdf](https://github.com/user-attachments/files/17388698/2AdiRiadi_2C3220005_TEKPANG.pdf)

**Comment by Rizkifajar5** [comment]
[Tugas2_2C3220008_Rizki Fajar R. (1).docx](https://github.com/user-attachments/files/17388739/Tugas2_2C3220008_Rizki.Fajar.R.1.docx)

**Comment by dilan1212** [comment]
[T2_dilan satria_2C3220007.pdf.pdf](https://github.com/user-attachments/files/17388738/T2_dilan.satria_2C3220007.pdf.pdf)

**Comment by Liana301103** [comment]
[T2_LIANA KUSWARDHANI_2C3220003.pdf](https://github.com/user-attachments/files/17388971/T2_LIANA.KUSWARDHANI_2C3220003.pdf)

**Comment by adiriadi04** [comment]
[T2_AdiRiadi_2C3220005_TEKPANG.pdf](https://github.com/user-attachments/files/17389126/T2_AdiRiadi_2C3220005_TEKPANG.pdf)
